### ISSUE TITLE
New feature list - Required in Udaan Post Editing tool.

### ISSUE THREAD

**Issue by Sadam452** [UDAAN-LEAP/leap-pe-tool#205]
- [x] Resize image by dragging its corners. 
- [x] Ordered and unordered list.
- [x] Large sets take time when opened first time in tool.
- [x] Saving a page takes time.
- [x] Cloud save is not working in few sets.
- [x] Project xml file gets corrupted when cloud save is successfull
- [x] Mark region not working in fresh sets
- [x]  Change login implementation so that Udaan credentials can be used to login.

**Comment by Sadam452** [comment]
**Please refer to following commits for their corresponding tasks.**
1. Task 6 : 54e3df11e6bbe1ca34a94071a9c16687a6b52528
2. Task 4 & 5 : 08804b1b6c9cb3b35de3681cf7fd82fcb156f6d7
3. Task 7 : 9fa622ad3560f8e1403d36a2d5eb86a9004cfa88
4. Task 2 : ea2de9bd055fad32c35bd526eecd3f4b00740cad
5. Task 8:  10e796e56eee0c6681e7782af4499882ace567d8

**Comment by Amman30** [comment]
Task 3:e9fe1392aac2f65fc53f5d1cfdabb6406c05a2bd

**Comment by Amman30** [comment]
Task 1:de90e30
