### ISSUE TITLE
UI fix on popup menu for the Tab widget

### ISSUE THREAD

**Issue by NishantWankhade** [UDAAN-LEAP/leap-pe-tool#296]
Inside the 1st tab of the tab widget, if you right click to copy SLP guide, That copy text is not clearly visible. 
![image](https://github.com/UDAAN-LEAP/leap-pe-tool/assets/82573863/ed3dc536-d506-4eff-a339-d9e7c3ea8b50)

**Comment by NishantWankhade** [comment]
Fixed at commit 4f69e9eeddcf58b24f3777e273da06d7e9c51e20 
Fixed one Bug at commit 2c1356e1ea241da90511799f44980bac8656de91

There are still some bugs in it. 
1- Just after starting the tool in SLP tab, the UI is still the same. 
2- After Selecting a word and clicking on copy the menu occurs again which should not be the case. 

Assigned to @saanvibehele.

**Comment by saanvibehele** [comment]
completed on commit number bba12ed

**Comment by NishantWankhade** [comment]
https://github.com/UDAAN-LEAP/leap-pe-tool/issues/296#issuecomment-1722670666
First bug is still there, for windows build. 
Please have a look into it once.

**Comment by NishantWankhade** [comment]
Reimplemented the whole task and made it optimized at commit number :- 918d923332380ec465ce7b154c3a015e5b377656
Just stylesheet is changed instead of code.
