### ISSUE TITLE
New feature to save user completed pages

### ISSUE THREAD

**Issue by NishantWankhade** [UDAAN-LEAP/leap-pe-tool#312]
We have tried implementing the corrected, verified and mark for review by saving them in a text files. However it was increasing the size of text files. 
Now we have to implement same feature however now we should add the to qsettings object for each different book of that user.

**Comment by NishantWankhade** [comment]
Expected Outcome of tasks :- 
- Add a checkbox similar to "Mark for review" in which one will be visible for corrector and another will be visible only for verifier
- Save the checked pages in a qsettings object, Which will have hierarchy as below
`IIT-B organization Setting object`
`|- Corrected Pages`
`|    |- Book Name 1`
`|         |- Page names`
`|- Verified Pages`
`     |- Book Name 1`
`          |- Page names`
- After opening the Project corresponding settings should be read and the status of the opened file should be reflected on checkbox
- After changing the pages that status of that page should also reflect on checkbox

**Comment by NishantWankhade** [comment]
Writing and reading of settings assigned to @AayushGupta69 
Handling status of the current page assigned to @saanvibehele

**Comment by NishantWankhade** [comment]
@AayushGupta69 
- Bug in checkbox i.e. that status checkbox should be disabled after closing the project ... Rather it would be better to set its visibility to false if no project is open.

**Comment by NishantWankhade** [comment]
@saanvibehele 
- Bug in verifier checkbox i.e. verifier is not able to check the verifier checkbox.

**Comment by saanvibehele** [comment]
bug fixed on commit: e8adbdd
task completed

**Comment by AayushGupta69** [comment]
Bug fixed on commit 3e24ca764a30a65ef8357ab2abe951dd6c1d567e

**Comment by NishantWankhade** [comment]
Assigned to @AayushGupta69 --- 
How to get the bug 
- Open any project
- Mark some pages as corrected
- Click on File -> Exit button 
- Reopen the tool and same project 
- You will see that it status is cleared

**Comment by NishantWankhade** [comment]
Assigned to @saanvibehele --- 
For corrector the checkbox must be enabled only when the current page opened is from folder "CorrectorOutput" 
Similarly for verifier that should be the case. 
And for rest of the folders from treeview it should be invisible.

**Comment by AayushGupta69** [comment]
**Update:**
- Refactored some code at commit bcbe026e5f9f78a13c240e6d175d3bbb87af41ad

- Fixed the bug at the commit 7c0bb1efe8138c2182a1e6d2298c519642916c53

There is still one bug left. When we open a project, the status of the checkbox does not update automatically even though the pages have been successfully read. We have to change the page from the treeView to update the checkbox and then it shows the status correctly.

**Comment by NishantWankhade** [comment]
Assigned to @AayushGupta69 
Bug 
- Open a project 
- Click on the page which is already marked 
- Close the project 
- Reopen the project
- You will notice that the current page was already marked however it was not showing the status just after opening the project 

After opening the project it should reflect the current page status also.

**Comment by NishantWankhade** [comment]
> **Update:**
> 
> * Refactored some code at commit [bcbe026](https://github.com/UDAAN-LEAP/leap-pe-tool/commit/bcbe026e5f9f78a13c240e6d175d3bbb87af41ad)
> * Fixed the bug at the commit [7c0bb1e](https://github.com/UDAAN-LEAP/leap-pe-tool/commit/7c0bb1efe8138c2182a1e6d2298c519642916c53)
> 
> There is still one bug left. When we open a project, the status of the checkbox does not update automatically even though the pages have been successfully read. We have to change the page from the treeView to update the checkbox and then it shows the status correctly.

You should set the status of current page in function RecentPageInfo which is called at the end of OpenProject.

**Comment by saanvibehele** [comment]
Fixed it at commit number: 58c7a37
The bug didn't exist on the branch userCompletedPages.
It was introduced during merge, but it fixed now as it was originally in userCompletedPages.

**Comment by AayushGupta69** [comment]
@NishantWankhade Fixed on commit fc39bf59ddfd7a67c223487069c7c4365e64cc38
