### ISSUE TITLE
Implementation of Comparing 2 versions of User pages

### ISSUE THREAD

**Issue by NishantWankhade** [UDAAN-LEAP/leap-pe-tool#318]
@AayushGupta69 You have to follow a procedure aligning the following one : 
1) You already have Commit Sha of particular sync so set the token for authorization into headers and give param as 'ref' = commit sha 
2) Set the api url as https://api.github.com/repos/UdaanContentForLogging/{repo_name}/contents/{mRole}Output
3) Send a get request to the Url 
4) You will receive JSON output , Render JSON Object in readable format - > Filter out html files -> For each html files there is 'download_url' key in json object store those download urls in a QMap with Page name as a Key and download url as a value
5) Now you have to send another network "get" request for the download Url of Selected page to get the text output from that. 

Download Url will be something like a "raw.githubusercontent.com" 

First network request will be sent when the user clicks on the compare version history or when he changes the commit number and at the same time the download url of all the pages will be stored in a QMap local variable inside the funciton. 

Second network request will be sent when the page numbers is changed.

**Comment by NishantWankhade** [comment]
There is bug in the impelementation. Once check the it.

**Comment by AayushGupta69** [comment]
Fixed the bug that was causing the contents of user pages to not display correctly when the local version was selected in the 'show diff' functionality on commit bca8cce94bd30cedca6d36a69d4df9b3d016cfc7
