### ISSUE TITLE
To load words-meaning from whole book in dictionary tab

### ISSUE THREAD

**Issue by NishantWankhade** [UDAAN-LEAP/leap-pe-tool#325]
Add a extra feature button on besides the "Add Custom Word" btn for loading all the words from the dict files of all the pages.

**Comment by AayushGupta69** [comment]
Completed on commit d515bd45c58171f1b5bb6c2c7fda7da5b4ded7e2 and improved on commit 4cb965a3a344b1c6b4365a7eabbf09f51a6dad69
